apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "rstudio.fullname" . }}
  labels:
    app: {{ include "rstudio.name" . }}
    chart: {{ include "rstudio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rstudio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "rstudio.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DISABLE_AUTH
              value: true
          ports:
            - name: http
              containerPort: 8787
              protocol: TCP
          volumeMounts:
            - name: data-vol
              mountPath: {{ .Values.storage.localMountPath }}
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: {{ include "rstudio.fullname" . }}-pvc
