{{- if .Values.storage.nfs -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rstudio.fullname" . }}-pvc
spec:
  storageClassName: rstudio-data
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.nfs.size }}
  volumeName: {{ include "rstudio.fullname" . }}-volume
{{- end }}
