apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rstudio-pvc
spec:
  storageClassName: rstudio-data
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.nfs.size }}
  volumeName: rstudio-volume